### ISSUE TITLE
Knock-off

### ISSUE THREAD

**Issue by host505** [Mr-invisibles/resources#1]
If you're going to knock-off my add-on at least have the decency to not replace credits with yours (it's not like you changed anything anyway) and USE YOUR OWN F'N API KEYS (tvdb, tmdb & fanart.tv)

**Comment by Mr-invisibles** [comment]
Was not ment to be uploaded on some public server was to test for my own use, but  i taken down and just on my own now kodi, and the api is changed to

So sorry for that..

**Comment by Mr-invisibles** [comment]
even took down the hole repo, because i will just use for testing purpose

**Comment by host505** [comment]
On the version you had on your repo only the trakt API key was changed.
There are also hardcoded API keys for tmdb, tvdb & fanart.tv, which are mine.
If you took it offline and you're the only one using it it's ok, but if others are using his add-on please change these as well ASAP.

**Comment by Mr-invisibles** [comment]
all done, and it not public anymore anyware
